# Generated by Django 4.1.4 on 2022-12-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='files/covers'),
            preserve_default=False,
        ),
    ]
