# Generated by Django 4.1.4 on 2022-12-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='default.jpg', upload_to='files/videos'),
            preserve_default=False,
        ),
    ]
