# Generated by Django 4.1.4 on 2023-01-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image_tags_video_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
    ]
