# Generated by Django 4.1.4 on 2023-01-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_image_tags_remove_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.TextField(),
        ),
    ]
