# Generated by Django 4.1.4 on 2023-01-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_image_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
