# Generated by Django 4.1.4 on 2023-01-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_video_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='Description...', max_length=400)),
                ('image', models.ImageField(upload_to='images')),
                ('owner', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
