# Generated by Django 4.1.4 on 2023-01-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_virtualtour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='cover',
            new_name='image',
        ),
    ]
